# Generated by Django 6.0.1 on 2026-01-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_size_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size_label',
            new_name='label',
        ),
        migrations.AddField(
            model_name='size',
            name='category_type',
            field=models.CharField(choices=[('kids', 'Kidswear'), ('women', "Women's Wear"), ('men', "Men's Wear")], default='kids', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('unisex', 'Unisex'), ('women', 'Women'), ('men', 'Men')], max_length=10),
        ),
    ]
